### ISSUE TITLE
Barcode Support

### ISSUE THREAD

**Issue by gnanakeethan** [knq/escpos#2]
I have been trying and customizing the code for printing barcode. I could not succeed in developing a proper solution. 

```php
<?php
/* ASCII constants */
const ESC = "\x1b";
const GS="\x1d";
const NUL="\x00";

/* Output an example receipt */
echo ESC."@"; // Reset to defaults
echo GS."k".chr(4)."123123".NUL; // Print barcode
echo ESC."d".chr(1); // Blank line
exit(0);
```
How should the above code be translated to go. I am missing something. I tried placing \x04 instead of 4 in middle. But it just prints empty line. 

```go
//barcode is string
func (e *Escpos) PrintBarcode(barcode string, format string) {
	e.Write(fmt.Sprintf("\x1dk4%v\x00", barcode))
}
```

**Comment by kenshaw** [comment]
The first ESC+@ is the same as the `Escpos.Init()` call.

I believe `echo GS."k".chr(4)."123123".NUL;` is `"\x1dk\x04123123\x00"` in Go.

And the last one, ESC+d+1 is the same as `Escpos.FormfeedN(1)`

**Comment by gnanakeethan** [comment]
Thanks for the help. Any idea about implementing this functionality natively in this package? It seems to be a good addition.

**Comment by kenshaw** [comment]
The printers I have don't support barcodes. I had already tried this when I first wrote the package. If your printer supports it, please test it and see if it works as expected. I would gladly merge a PR supporting this, if I had reasonable assurance that it had been tested properly.

**Comment by gnanakeethan** [comment]
It works. The following code worked perfectly for printing digits / chars either(7 max). I am just a noob at Golang. 
I will put up a PR as soon as I verify. 
```go
func (e *Escpos) PrintBarcode(barcode string, format string) {
	barcode = strings.ToUpper(barcode)
	e.Write("\x1dk\x04" + barcode + "\x00")
}
```
I gathered stuff from http://content.epson.de/fileadmin/content/files/RSD/downloads/escpos.pdf

format needs to be converted to HEX. 
A PHP implementation exists in the following link. 
https://github.com/mike42/escpos-php/blob/master/src/Mike42/Escpos/Printer.php#L382

**Comment by kenshaw** [comment]
I added a simple `Escpos.Barcode` func. However, as I stated before, I can't really test it since the printers I own don't support barcodes. I would like to rewrite this whole thing, as I haven't really looked at the code in this package in almost 2 years.
